MAKE="make ARCH=x86_64 KERNELVER=$kernelver"
CLEAN="make ARCH=x86_64 KERNELVER=$kernelver clean"
BUILT_MODULE_NAME[0]="mtgpu"
DEST_MODULE_LOCATION[0]="/extra"
PACKAGE_NAME=mtgpu-dkms
PACKAGE_VERSION=3.0.0
REMAKE_INITRD=no
AUTOINSTALL="yes"
PRE_INSTALL="dkms.pre_install $kernelver"
POST_REMOVE="dkms.post_remove $kernelver"
POST_INSTALL="dkms.post_install"
